# Load environment variables, set dynamic variables, and make
# them available to child shells.

include .env # caution: does not work for multiline values
GO_COMPILER_CACHE = $(shell go env GOCACHE)
REALWORLD_HOST_DATA_DIR = $(shell pwd)/data
export
